config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :relationships, only: [:create, :destroy]
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :posts, only:[:show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :favorite_relationships, only: [:create, :destroy]
  resources :notifications, only: :index

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorite_relationships, dependent: :destroy
  has_many :liked_by, through: :favorite_relationships, source: :user
  has_many :notifications, dependent: :destroy
  has_many :post_category_relations
  has_many :categories, through: :post_category_relations
  has_one_attached :image
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum:1000}
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }

  def display_image
    image.variant(resize_to_limit: [400, 400])
  end

  def create_notification_like!(current_user)
    # すでにいいねされているか検索
    temp_notifications = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp_notifications.blank?
      notification = current_user.active_notifications.build(
        post_id: id, visited_id: user_id, action: 'like'
      )
      # 自分の投稿に対する良いねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notifications.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    notification_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    notification_ids.each do |notification_id|
      save_notification_comment!(current_user, comment_id, notification_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if notification_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                      params: { controller: :pages, action: :index } %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with model: @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <p>
    <%= f.label :category, 'カテゴリ' %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
  </p>
  <div>
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

  <script type="text/javascript">
    $("#post_image").bind("change", function() {
      var size_in_megabytes = this.files[0].size / 1024 / 1024;
      if (size_in_megabytes > 5) {
        alert("Maximum file size is 5MB. Please choose a smaller file.");
        $("#post_image").val("");
      }
    });
  </script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= likes_user_path(@user) %>">
    <strong id="likes" class="stat">
      <%= @user.likes.count %>
    </strong>
    likes
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.username %></h1>
<span><%= link_to "ユーザーページ", current_user %></span>
<span><%= pluralize(current_user.posts.count, "Posts") %></span>