config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :relationships, only: [:create, :destroy]
  devise_scope :user do
  post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :posts, only:[:show, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :favorite_relationships, only: [:create, :destroy]
  resources :notifications, only: :index

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BakeUp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav>
      <% if user_signed_in? %>
      <strong><%= link_to current_user.username, user_path(current_user) %></strong>
      <%= link_to 'プロフィール変更', edit_user_registration_path %>
      <%= link_to "ホームへ戻る", root_url %>
      <%= link_to "Users", users_path %>
      <%= link_to '通知', notifications_path, class:"btn"  %>
        <% if unchecked_notifications.any? %>
          <i class="fa fa-circle notification-circle"></i>
        <% end %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
       <% else %>
          <%= link_to 'サインアップ', new_user_registration_path %>
          <%= link_to 'ログイン', new_user_session_path %>
       <% end %>
    </nav>
  </header>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%
=begin%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%
=end%>

  <%= yield %>
</body>

</html>